[package]
name = "linux-wifi-utility"
version = "2.1.2"

[dependencies]
aes = "0.8.4"
chacha20 = "0.9.1"
clap = { version = "4.5.38", features = ["derive"] }
rand = "0.9.1"
rand_chacha = "0.9.0"
rand_seeder = "0.4.0"
serde = { version = "1.0.219", features = ["derive"] }

[[bin]]
name = "wifi-utility"
path = "main.rs"
